{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "e140ac19",
   "metadata": {},
   "source": [
    "# ATP Tennis Match Predictor — Clean Training Notebook\n",
    "\n",
    "Run cells top to bottom in order. Each section is clearly labelled.\n",
    "\n",
    "**Estimated total runtime:** ~8 minutes (feature build is the slow step)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "e34056c7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "All imports OK\n"
     ]
    }
   ],
   "source": [
    "# ═══════════════════════════════════════════\n",
    "# CELL 1 — ALL IMPORTS (run this first)\n",
    "# ═══════════════════════════════════════════\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import glob\n",
    "import os\n",
    "import json\n",
    "import joblib\n",
    "from collections import defaultdict, deque\n",
    "from tqdm import tqdm\n",
    "\n",
    "from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier\n",
    "from sklearn.metrics import accuracy_score, roc_auc_score, log_loss, brier_score_loss\n",
    "from sklearn.model_selection import ParameterGrid\n",
    "\n",
    "print(\"All imports OK\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c8f93713",
   "metadata": {},
   "source": [
    "## Step 1 — Load & Clean Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "86349751",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Files found:\n",
      " - ../data/2015.csv\n",
      " - ../data/2016.csv\n",
      " - ../data/2017.csv\n",
      " - ../data/2018.csv\n",
      " - ../data/2019.csv\n",
      " - ../data/2020.csv\n",
      " - ../data/2021.csv\n",
      " - ../data/2022.csv\n",
      " - ../data/2023.csv\n",
      " - ../data/2024.csv\n",
      " - ../data/2025.csv\n",
      " - ../data/2026.csv\n",
      "\n",
      "Raw shape: (31629, 51)\n"
     ]
    }
   ],
   "source": [
    "# ═══════════════════════════════════════════\n",
    "# CELL 2 — LOAD ALL CSVs (2015–2026)\n",
    "# ═══════════════════════════════════════════\n",
    "files = glob.glob('../data/20[1-2]*.csv')\n",
    "files = [f for f in files if os.path.basename(f).replace('.csv', '').isdigit()]\n",
    "files = [f for f in files if int(os.path.basename(f).replace('.csv', '')) >= 2015]\n",
    "files.sort()\n",
    "\n",
    "print(\"Files found:\")\n",
    "for f in files:\n",
    "    print(\" -\", f)\n",
    "\n",
    "dfs = []\n",
    "for f in files:\n",
    "    year_df = pd.read_csv(f)\n",
    "    year_df['source_file'] = os.path.basename(f)\n",
    "    dfs.append(year_df)\n",
    "\n",
    "df = pd.concat(dfs, ignore_index=True)\n",
    "\n",
    "# Drop duplicate header rows (some CSVs have them mid-file)\n",
    "df = df[df['tourney_date'] != 'tourney_date']\n",
    "\n",
    "print(f\"\\nRaw shape: {df.shape}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "12a09633",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Numeric columns cast OK\n",
      "winner_rank    float64\n",
      "loser_rank     float64\n",
      "winner_age     float64\n",
      "dtype: object\n",
      "Cleaned shape: (29922, 57)\n",
      "Date range: 2015-01-04 → 2026-04-05\n"
     ]
    }
   ],
   "source": [
    "# ═══════════════════════════════════════════\n",
    "# CELL 3 — CLEAN & ENCODE\n",
    "# ═══════════════════════════════════════════\n",
    "df['tourney_date'] = pd.to_datetime(df['tourney_date'], format='%Y%m%d', errors='coerce')\n",
    "df = df.dropna(subset=['tourney_date']).copy()\n",
    "df = df.dropna(subset=['winner_rank', 'loser_rank', 'winner_age', 'loser_age']).copy()\n",
    "\n",
    "df['winner_rank_points'] = pd.to_numeric(df['winner_rank_points'], errors='coerce').fillna(0)\n",
    "df['loser_rank_points']  = pd.to_numeric(df['loser_rank_points'],  errors='coerce').fillna(0)\n",
    "df['indoor'] = df['indoor'].fillna('O')\n",
    "\n",
    "# Drop walkovers and retirements\n",
    "df = df[~df['score'].str.contains('W/O|RET', na=False)].copy()\n",
    "\n",
    "# Drop NaN player IDs\n",
    "df = df.dropna(subset=['winner_id', 'loser_id']).copy()\n",
    "df = df[df['winner_id'].astype(str) != 'nan'].copy()\n",
    "df = df[df['loser_id'].astype(str)  != 'nan'].copy()\n",
    "\n",
    "surface_map = {'Hard': 0, 'Clay': 1, 'Grass': 2, 'Carpet': 0}\n",
    "level_map   = {'250': 0, '500': 1, 'A': 2, 'M': 3, 'G': 4, 'D': 5, 'O': 5, 'F': 6}\n",
    "indoor_map  = {'O': 0, 'I': 1}\n",
    "round_map   = {'RR': 0, 'R128': 1, 'R64': 2, 'R32': 3, 'R16': 4, 'QF': 5, 'SF': 6, 'F': 7, 'BR': 6}\n",
    "\n",
    "df['surface_enc'] = df['surface'].map(surface_map)\n",
    "df['level_enc']   = df['tourney_level'].astype(str).map(level_map)\n",
    "df['indoor_enc']  = df['indoor'].map(indoor_map)\n",
    "df['round_enc']   = df['round'].map(round_map)\n",
    "\n",
    "df = df.dropna(subset=['surface_enc', 'level_enc', 'indoor_enc', 'round_enc', 'best_of']).copy()\n",
    "\n",
    "df['year'] = df['tourney_date'].dt.year\n",
    "if 'match_num' in df.columns:\n",
    "    df['match_id'] = df['tourney_id'].astype(str) + '_' + df['match_num'].astype(str)\n",
    "else:\n",
    "    df['match_id'] = df['tourney_id'].astype(str) + '_' + df.index.astype(str)\n",
    "\n",
    "df = df.sort_values(['tourney_date', 'match_id']).reset_index(drop=True)\n",
    "\n",
    "for col in ['winner_rank', 'loser_rank', 'winner_rank_points', 'loser_rank_points',\n",
    "            'winner_age', 'loser_age']:\n",
    "    df[col] = pd.to_numeric(df[col], errors='coerce')\n",
    "\n",
    "df = df.dropna(subset=['winner_rank', 'loser_rank', 'winner_age', 'loser_age']).copy()\n",
    "print(\"Numeric columns cast OK\")\n",
    "print(df[['winner_rank','loser_rank','winner_age']].dtypes)\n",
    "\n",
    "print(f\"Cleaned shape: {df.shape}\")\n",
    "print(f\"Date range: {df['tourney_date'].min().date()} → {df['tourney_date'].max().date()}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "097a8a71",
   "metadata": {},
   "source": [
    "## Step 2 — Feature Engineering"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "0a732f11",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Helpers defined\n"
     ]
    }
   ],
   "source": [
    "# ═══════════════════════════════════════════\n",
    "# CELL 4 — HELPER FUNCTIONS\n",
    "# ═══════════════════════════════════════════\n",
    "def smoothed_wr(wins, matches, prior_wins=2.5, prior_matches=5):\n",
    "    return (wins + prior_wins) / (matches + prior_matches)\n",
    "\n",
    "def expected_score(r1, r2):\n",
    "    return 1 / (1 + 10 ** ((r2 - r1) / 400))\n",
    "\n",
    "def update_elo(r1, r2, score1, k=32):\n",
    "    e1 = expected_score(r1, r2)\n",
    "    new_r1 = r1 + k * (score1 - e1)\n",
    "    new_r2 = r2 + k * ((1 - score1) - (1 - e1))\n",
    "    return new_r1, new_r2\n",
    "\n",
    "def days_since(last_date, current_date, default_days=30):\n",
    "    if pd.isna(last_date):\n",
    "        return default_days\n",
    "    return min((current_date - last_date).days, 60)\n",
    "\n",
    "def prune_old_dates(date_deque, current_date, window_days):\n",
    "    while date_deque and (current_date - date_deque[0]).days > window_days:\n",
    "        date_deque.popleft()\n",
    "\n",
    "print(\"Helpers defined\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "b50e8f1a",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████████████████████████████████████████████████████████████████| 29922/29922 [00:00<00:00, 48780.82it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "feature_df shape: (29922, 36)\n"
     ]
    }
   ],
   "source": [
    "# ═══════════════════════════════════════════\n",
    "# CELL 5 — BUILD FEATURES (~3 minutes)\n",
    "# ═══════════════════════════════════════════\n",
    "recent_results         = defaultdict(lambda: deque(maxlen=10))\n",
    "recent_surface_results = defaultdict(lambda: deque(maxlen=10))\n",
    "wins_by_pair           = defaultdict(int)\n",
    "wins_by_pair_surface   = defaultdict(int)\n",
    "last_match_date        = {}\n",
    "recent_dates_7         = defaultdict(deque)\n",
    "recent_dates_30        = defaultdict(deque)\n",
    "elo                    = defaultdict(lambda: 1500.0)\n",
    "elo_surface            = defaultdict(lambda: 1500.0)\n",
    "\n",
    "feature_rows = []\n",
    "\n",
    "for row in tqdm(df.itertuples(index=False), total=len(df)):\n",
    "    date = row.tourney_date\n",
    "    surf = int(row.surface_enc)\n",
    "    w = row.winner_id\n",
    "    l = row.loser_id\n",
    "\n",
    "    w_hist = recent_results[w]; l_hist = recent_results[l]\n",
    "    w_recent_wr = smoothed_wr(sum(w_hist), len(w_hist))\n",
    "    l_recent_wr = smoothed_wr(sum(l_hist), len(l_hist))\n",
    "\n",
    "    w_s_hist = recent_surface_results[(w, surf)]; l_s_hist = recent_surface_results[(l, surf)]\n",
    "    w_surface_wr = smoothed_wr(sum(w_s_hist), len(w_s_hist))\n",
    "    l_surface_wr = smoothed_wr(sum(l_s_hist), len(l_s_hist))\n",
    "\n",
    "    w_h2h_wins = wins_by_pair[(w, l)]; l_h2h_wins = wins_by_pair[(l, w)]\n",
    "    total_h2h = w_h2h_wins + l_h2h_wins\n",
    "    w_h2h_wr = (w_h2h_wins + 1) / (total_h2h + 2)\n",
    "\n",
    "    w_h2h_s_wins = wins_by_pair_surface[(w, l, surf)]; l_h2h_s_wins = wins_by_pair_surface[(l, w, surf)]\n",
    "    total_h2h_surface = w_h2h_s_wins + l_h2h_s_wins\n",
    "    w_h2h_surface_wr = (w_h2h_s_wins + 1) / (total_h2h_surface + 2)\n",
    "\n",
    "    prune_old_dates(recent_dates_7[w], date, 7); prune_old_dates(recent_dates_7[l], date, 7)\n",
    "    prune_old_dates(recent_dates_30[w], date, 30); prune_old_dates(recent_dates_30[l], date, 30)\n",
    "\n",
    "    w_elo = elo[w]; l_elo = elo[l]\n",
    "    w_surface_elo = elo_surface[(w, surf)]; l_surface_elo = elo_surface[(l, surf)]\n",
    "\n",
    "    feature_rows.append({\n",
    "        'match_id': row.match_id, 'match_date': date, 'year': row.year,\n",
    "        'winner_rank': row.winner_rank, 'loser_rank': row.loser_rank,\n",
    "        'winner_rank_points': row.winner_rank_points, 'loser_rank_points': row.loser_rank_points,\n",
    "        'winner_age': row.winner_age, 'loser_age': row.loser_age,\n",
    "        'surface_enc': row.surface_enc, 'level_enc': row.level_enc,\n",
    "        'indoor_enc': row.indoor_enc, 'round_enc': row.round_enc, 'best_of': row.best_of,\n",
    "        'w_recent_wr': w_recent_wr, 'l_recent_wr': l_recent_wr,\n",
    "        'w_recent_n': len(w_hist), 'l_recent_n': len(l_hist),\n",
    "        'w_surface_wr': w_surface_wr, 'l_surface_wr': l_surface_wr,\n",
    "        'w_surface_n': len(w_s_hist), 'l_surface_n': len(l_s_hist),\n",
    "        'w_h2h_wr': w_h2h_wr, 'total_h2h': total_h2h,\n",
    "        'w_h2h_surface_wr': w_h2h_surface_wr, 'total_h2h_surface': total_h2h_surface,\n",
    "        'w_days_rest': days_since(last_match_date.get(w), date),\n",
    "        'l_days_rest': days_since(last_match_date.get(l), date),\n",
    "        'w_matches_7d': len(recent_dates_7[w]), 'l_matches_7d': len(recent_dates_7[l]),\n",
    "        'w_matches_30d': len(recent_dates_30[w]), 'l_matches_30d': len(recent_dates_30[l]),\n",
    "        'w_elo': w_elo, 'l_elo': l_elo,\n",
    "        'w_surface_elo': w_surface_elo, 'l_surface_elo': l_surface_elo,\n",
    "    })\n",
    "\n",
    "    recent_results[w].append(1); recent_results[l].append(0)\n",
    "    recent_surface_results[(w, surf)].append(1); recent_surface_results[(l, surf)].append(0)\n",
    "    wins_by_pair[(w, l)] += 1; wins_by_pair_surface[(w, l, surf)] += 1\n",
    "    recent_dates_7[w].append(date); recent_dates_7[l].append(date)\n",
    "    recent_dates_30[w].append(date); recent_dates_30[l].append(date)\n",
    "    last_match_date[w] = date; last_match_date[l] = date\n",
    "    elo[w], elo[l] = update_elo(w_elo, l_elo, 1)\n",
    "    elo_surface[(w, surf)], elo_surface[(l, surf)] = update_elo(w_surface_elo, l_surface_elo, 1)\n",
    "\n",
    "feature_df = pd.DataFrame(feature_rows)\n",
    "print(f\"feature_df shape: {feature_df.shape}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "3ff5f1d7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "model_df_v2 shape: (59844, 51)\n",
      "Target distribution: {1: 29922, 0: 29922}\n"
     ]
    }
   ],
   "source": [
    "# ═══════════════════════════════════════════\n",
    "# CELL 6 — MIRROR INTO TRAINING ROWS (explicit, no flip logic)\n",
    "# ═══════════════════════════════════════════\n",
    "rows = []\n",
    "for row in feature_df.itertuples(index=False):\n",
    "    base = {\n",
    "        'match_id': row.match_id, 'match_date': row.match_date, 'year': row.year,\n",
    "        'surface': row.surface_enc, 'level': row.level_enc,\n",
    "        'indoor': row.indoor_enc, 'round': row.round_enc, 'best_of': row.best_of,\n",
    "    }\n",
    "\n",
    "    # ── Winner as p1, target = 1 ──────────────────────────────\n",
    "    rows.append({**base,\n",
    "        'p1_rank': row.winner_rank, 'p2_rank': row.loser_rank,\n",
    "        'rank_diff': row.loser_rank - row.winner_rank,\n",
    "        'p1_rank_points': row.winner_rank_points, 'p2_rank_points': row.loser_rank_points,\n",
    "        'rank_points_diff': row.winner_rank_points - row.loser_rank_points,\n",
    "        'p1_age': row.winner_age, 'p2_age': row.loser_age,\n",
    "        'age_diff': row.winner_age - row.loser_age,\n",
    "        'p1_recent_wr': row.w_recent_wr, 'p2_recent_wr': row.l_recent_wr,\n",
    "        'recent_wr_diff': row.w_recent_wr - row.l_recent_wr,\n",
    "        'p1_recent_n': row.w_recent_n, 'p2_recent_n': row.l_recent_n,\n",
    "        'p1_surface_wr': row.w_surface_wr, 'p2_surface_wr': row.l_surface_wr,\n",
    "        'surface_wr_diff': row.w_surface_wr - row.l_surface_wr,\n",
    "        'p1_surface_n': row.w_surface_n, 'p2_surface_n': row.l_surface_n,\n",
    "        'p1_h2h_wr': row.w_h2h_wr, 'p2_h2h_wr': 1 - row.w_h2h_wr,\n",
    "        'h2h_diff': row.w_h2h_wr - (1 - row.w_h2h_wr),\n",
    "        'p1_h2h_n': row.total_h2h,\n",
    "        'p1_h2h_surface_wr': row.w_h2h_surface_wr, 'p2_h2h_surface_wr': 1 - row.w_h2h_surface_wr,\n",
    "        'h2h_surface_diff': row.w_h2h_surface_wr - (1 - row.w_h2h_surface_wr),\n",
    "        'p1_h2h_surface_n': row.total_h2h_surface,\n",
    "        'p1_days_rest': row.w_days_rest, 'p2_days_rest': row.l_days_rest,\n",
    "        'rest_diff': row.w_days_rest - row.l_days_rest,\n",
    "        'p1_matches_7d': row.w_matches_7d, 'p2_matches_7d': row.l_matches_7d,\n",
    "        'matches_7d_diff': row.w_matches_7d - row.l_matches_7d,\n",
    "        'p1_matches_30d': row.w_matches_30d, 'p2_matches_30d': row.l_matches_30d,\n",
    "        'matches_30d_diff': row.w_matches_30d - row.l_matches_30d,\n",
    "        'p1_elo': row.w_elo, 'p2_elo': row.l_elo,\n",
    "        'elo_diff': row.w_elo - row.l_elo,\n",
    "        'p1_surface_elo': row.w_surface_elo, 'p2_surface_elo': row.l_surface_elo,\n",
    "        'surface_elo_diff': row.w_surface_elo - row.l_surface_elo,\n",
    "        'target': 1,\n",
    "    })\n",
    "\n",
    "    # ── Loser as p1, target = 0 ───────────────────────────────\n",
    "    rows.append({**base,\n",
    "        'p1_rank': row.loser_rank, 'p2_rank': row.winner_rank,\n",
    "        'rank_diff': row.winner_rank - row.loser_rank,\n",
    "        'p1_rank_points': row.loser_rank_points, 'p2_rank_points': row.winner_rank_points,\n",
    "        'rank_points_diff': row.loser_rank_points - row.winner_rank_points,\n",
    "        'p1_age': row.loser_age, 'p2_age': row.winner_age,\n",
    "        'age_diff': row.loser_age - row.winner_age,\n",
    "        'p1_recent_wr': row.l_recent_wr, 'p2_recent_wr': row.w_recent_wr,\n",
    "        'recent_wr_diff': row.l_recent_wr - row.w_recent_wr,\n",
    "        'p1_recent_n': row.l_recent_n, 'p2_recent_n': row.w_recent_n,\n",
    "        'p1_surface_wr': row.l_surface_wr, 'p2_surface_wr': row.w_surface_wr,\n",
    "        'surface_wr_diff': row.l_surface_wr - row.w_surface_wr,\n",
    "        'p1_surface_n': row.l_surface_n, 'p2_surface_n': row.w_surface_n,\n",
    "        'p1_h2h_wr': 1 - row.w_h2h_wr, 'p2_h2h_wr': row.w_h2h_wr,\n",
    "        'h2h_diff': (1 - row.w_h2h_wr) - row.w_h2h_wr,\n",
    "        'p1_h2h_n': row.total_h2h,\n",
    "        'p1_h2h_surface_wr': 1 - row.w_h2h_surface_wr, 'p2_h2h_surface_wr': row.w_h2h_surface_wr,\n",
    "        'h2h_surface_diff': (1 - row.w_h2h_surface_wr) - row.w_h2h_surface_wr,\n",
    "        'p1_h2h_surface_n': row.total_h2h_surface,\n",
    "        'p1_days_rest': row.l_days_rest, 'p2_days_rest': row.w_days_rest,\n",
    "        'rest_diff': row.l_days_rest - row.w_days_rest,\n",
    "        'p1_matches_7d': row.l_matches_7d, 'p2_matches_7d': row.w_matches_7d,\n",
    "        'matches_7d_diff': row.l_matches_7d - row.w_matches_7d,\n",
    "        'p1_matches_30d': row.l_matches_30d, 'p2_matches_30d': row.w_matches_30d,\n",
    "        'matches_30d_diff': row.l_matches_30d - row.w_matches_30d,\n",
    "        'p1_elo': row.l_elo, 'p2_elo': row.w_elo,\n",
    "        'elo_diff': row.l_elo - row.w_elo,\n",
    "        'p1_surface_elo': row.l_surface_elo, 'p2_surface_elo': row.w_surface_elo,\n",
    "        'surface_elo_diff': row.l_surface_elo - row.w_surface_elo,\n",
    "        'target': 0,\n",
    "    })\n",
    "\n",
    "model_df_v2 = pd.DataFrame(rows)\n",
    "print(f\"model_df_v2 shape: {model_df_v2.shape}\")\n",
    "print(f\"Target distribution: {model_df_v2['target'].value_counts().to_dict()}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b6b461a9",
   "metadata": {},
   "source": [
    "## Step 3 — Train / Val / Test Split"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "0b684486",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Train: (41142, 47)  (2015-01-04 → 2022-11-27)\n",
      "Val:   (5638, 47)  (2023-01-02 → 2023-11-27)\n",
      "Test:  (13064, 47)  (2024-01-01 → 2026-04-05)\n"
     ]
    }
   ],
   "source": [
    "# ═══════════════════════════════════════════\n",
    "# CELL 7 — TEMPORAL SPLIT + FEATURE COLS\n",
    "# ═══════════════════════════════════════════\n",
    "feature_cols = [\n",
    "    'p1_rank', 'p2_rank', 'rank_diff',\n",
    "    'p1_rank_points', 'p2_rank_points', 'rank_points_diff',\n",
    "    'p1_age', 'p2_age', 'age_diff',\n",
    "    'surface', 'level', 'indoor', 'round', 'best_of',\n",
    "    'p1_recent_wr', 'p2_recent_wr', 'recent_wr_diff',\n",
    "    'p1_recent_n', 'p2_recent_n',\n",
    "    'p1_surface_wr', 'p2_surface_wr', 'surface_wr_diff',\n",
    "    'p1_surface_n', 'p2_surface_n',\n",
    "    'p1_h2h_wr', 'p2_h2h_wr', 'h2h_diff', 'p1_h2h_n',\n",
    "    'p1_h2h_surface_wr', 'p2_h2h_surface_wr', 'h2h_surface_diff', 'p1_h2h_surface_n',\n",
    "    'p1_days_rest', 'p2_days_rest', 'rest_diff',\n",
    "    'p1_matches_7d', 'p2_matches_7d', 'matches_7d_diff',\n",
    "    'p1_matches_30d', 'p2_matches_30d', 'matches_30d_diff',\n",
    "    'p1_elo', 'p2_elo', 'elo_diff',\n",
    "    'p1_surface_elo', 'p2_surface_elo', 'surface_elo_diff',\n",
    "]\n",
    "\n",
    "train_df = model_df_v2[model_df_v2['match_date'] < '2023-01-01'].copy()\n",
    "val_df   = model_df_v2[(model_df_v2['match_date'] >= '2023-01-01') &\n",
    "                        (model_df_v2['match_date'] <  '2024-01-01')].copy()\n",
    "test_df  = model_df_v2[model_df_v2['match_date'] >= '2024-01-01'].copy()\n",
    "\n",
    "X_train, y_train = train_df[feature_cols], train_df['target']\n",
    "X_val,   y_val   = val_df[feature_cols],   val_df['target']\n",
    "X_test,  y_test  = test_df[feature_cols],  test_df['target']\n",
    "\n",
    "print(f\"Train: {X_train.shape}  ({train_df['match_date'].min().date()} → {train_df['match_date'].max().date()})\")\n",
    "print(f\"Val:   {X_val.shape}  ({val_df['match_date'].min().date()} → {val_df['match_date'].max().date()})\")\n",
    "print(f\"Test:  {X_test.shape}  ({test_df['match_date'].min().date()} → {test_df['match_date'].max().date()})\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "df4aad73",
   "metadata": {},
   "source": [
    "## Step 4 — Evaluation Helper"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "095b1f91",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "evaluate_binary_model defined\n"
     ]
    }
   ],
   "source": [
    "# ═══════════════════════════════════════════\n",
    "# CELL 8 — EVALUATION FUNCTION\n",
    "# ═══════════════════════════════════════════\n",
    "def evaluate_binary_model(model, X, y, label='set'):\n",
    "    proba = model.predict_proba(X)[:, 1]\n",
    "    pred  = (proba >= 0.5).astype(int)\n",
    "    return {\n",
    "        'set':      label,\n",
    "        'accuracy': accuracy_score(y, pred),\n",
    "        'auc':      roc_auc_score(y, proba),\n",
    "        'log_loss': log_loss(y, proba),\n",
    "        'brier':    brier_score_loss(y, proba),\n",
    "    }\n",
    "\n",
    "print(\"evaluate_binary_model defined\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "28311373",
   "metadata": {},
   "source": [
    "## Step 5 — Baseline Model (original params)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "d02295f7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Baseline results:\n",
      "           set  accuracy      auc  log_loss\n",
      "train_baseline  0.839847 0.935862  0.318985\n",
      "  val_baseline  0.804718 0.908220  0.365056\n",
      " test_baseline  0.802740 0.903801  0.373176\n"
     ]
    }
   ],
   "source": [
    "# ═══════════════════════════════════════════\n",
    "# CELL 9 — BASELINE WITH ORIGINAL PARAMS\n",
    "# ═══════════════════════════════════════════\n",
    "baseline_params = {\n",
    "    'learning_rate': 0.08, 'max_depth': 5, 'max_leaf_nodes': 31,\n",
    "    'min_samples_leaf': 20, 'l2_regularization': 0.0, 'max_iter': 300\n",
    "}\n",
    "\n",
    "baseline_hgb = HistGradientBoostingClassifier(random_state=42, **baseline_params)\n",
    "baseline_hgb.fit(X_train, y_train)\n",
    "\n",
    "baseline_results = pd.DataFrame([\n",
    "    evaluate_binary_model(baseline_hgb, X_train, y_train, 'train_baseline'),\n",
    "    evaluate_binary_model(baseline_hgb, X_val,   y_val,   'val_baseline'),\n",
    "    evaluate_binary_model(baseline_hgb, X_test,  y_test,  'test_baseline'),\n",
    "])\n",
    "print(\"Baseline results:\")\n",
    "print(baseline_results[['set','accuracy','auc','log_loss']].to_string(index=False))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4c0381d9",
   "metadata": {},
   "source": [
    "## Step 6 — Expanded Hyperparameter Search\n",
    "\n",
    "> ⚠️ This cell runs ~300 model fits. Expect **10–15 minutes**."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "90272625",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total combinations: 3840\n",
      "  50/3840 done — best AUC so far: 0.90185\n",
      "  100/3840 done — best AUC so far: 0.90618\n",
      "  150/3840 done — best AUC so far: 0.90820\n",
      "  200/3840 done — best AUC so far: 0.90921\n",
      "  250/3840 done — best AUC so far: 0.90921\n",
      "  300/3840 done — best AUC so far: 0.90921\n",
      "  350/3840 done — best AUC so far: 0.90937\n",
      "  400/3840 done — best AUC so far: 0.90941\n",
      "  450/3840 done — best AUC so far: 0.90941\n",
      "  500/3840 done — best AUC so far: 0.90941\n",
      "  550/3840 done — best AUC so far: 0.90941\n",
      "  600/3840 done — best AUC so far: 0.90941\n",
      "  650/3840 done — best AUC so far: 0.90941\n",
      "  700/3840 done — best AUC so far: 0.90941\n",
      "  750/3840 done — best AUC so far: 0.90941\n",
      "  800/3840 done — best AUC so far: 0.90941\n",
      "  850/3840 done — best AUC so far: 0.90941\n",
      "  900/3840 done — best AUC so far: 0.90941\n",
      "  950/3840 done — best AUC so far: 0.90941\n",
      "  1000/3840 done — best AUC so far: 0.90941\n",
      "  1050/3840 done — best AUC so far: 0.90941\n",
      "  1100/3840 done — best AUC so far: 0.90941\n",
      "  1150/3840 done — best AUC so far: 0.90941\n",
      "  1200/3840 done — best AUC so far: 0.90941\n",
      "  1250/3840 done — best AUC so far: 0.90941\n",
      "  1300/3840 done — best AUC so far: 0.90941\n",
      "  1350/3840 done — best AUC so far: 0.90973\n",
      "  1400/3840 done — best AUC so far: 0.90973\n",
      "  1450/3840 done — best AUC so far: 0.90973\n",
      "  1500/3840 done — best AUC so far: 0.90973\n",
      "  1550/3840 done — best AUC so far: 0.90973\n",
      "  1600/3840 done — best AUC so far: 0.90973\n",
      "  1650/3840 done — best AUC so far: 0.90973\n",
      "  1700/3840 done — best AUC so far: 0.90973\n",
      "  1750/3840 done — best AUC so far: 0.90973\n",
      "  1800/3840 done — best AUC so far: 0.90973\n",
      "  1850/3840 done — best AUC so far: 0.90973\n",
      "  1900/3840 done — best AUC so far: 0.90973\n",
      "  1950/3840 done — best AUC so far: 0.90973\n",
      "  2000/3840 done — best AUC so far: 0.90973\n",
      "  2050/3840 done — best AUC so far: 0.90973\n",
      "  2100/3840 done — best AUC so far: 0.90973\n",
      "  2150/3840 done — best AUC so far: 0.90973\n",
      "  2200/3840 done — best AUC so far: 0.90973\n",
      "  2250/3840 done — best AUC so far: 0.90973\n",
      "  2300/3840 done — best AUC so far: 0.90973\n",
      "  2350/3840 done — best AUC so far: 0.90973\n",
      "  2400/3840 done — best AUC so far: 0.90973\n",
      "  2450/3840 done — best AUC so far: 0.90973\n",
      "  2500/3840 done — best AUC so far: 0.90973\n",
      "  2550/3840 done — best AUC so far: 0.90973\n",
      "  2600/3840 done — best AUC so far: 0.90973\n",
      "  2650/3840 done — best AUC so far: 0.90973\n",
      "  2700/3840 done — best AUC so far: 0.90973\n",
      "  2750/3840 done — best AUC so far: 0.90973\n",
      "  2800/3840 done — best AUC so far: 0.90973\n",
      "  2850/3840 done — best AUC so far: 0.90973\n",
      "  2900/3840 done — best AUC so far: 0.90973\n",
      "  2950/3840 done — best AUC so far: 0.90973\n",
      "  3000/3840 done — best AUC so far: 0.90973\n",
      "  3050/3840 done — best AUC so far: 0.90973\n",
      "  3100/3840 done — best AUC so far: 0.90973\n",
      "  3150/3840 done — best AUC so far: 0.90973\n",
      "  3200/3840 done — best AUC so far: 0.90973\n",
      "  3250/3840 done — best AUC so far: 0.90973\n",
      "  3300/3840 done — best AUC so far: 0.90973\n",
      "  3350/3840 done — best AUC so far: 0.90973\n",
      "  3400/3840 done — best AUC so far: 0.90973\n",
      "  3450/3840 done — best AUC so far: 0.90973\n",
      "  3500/3840 done — best AUC so far: 0.90973\n",
      "  3550/3840 done — best AUC so far: 0.90973\n",
      "  3600/3840 done — best AUC so far: 0.90973\n",
      "  3650/3840 done — best AUC so far: 0.90973\n",
      "  3700/3840 done — best AUC so far: 0.90973\n",
      "  3750/3840 done — best AUC so far: 0.90973\n",
      "  3800/3840 done — best AUC so far: 0.90973\n",
      "\n",
      "Top 10 configurations by val AUC:\n",
      " learning_rate  max_depth  max_leaf_nodes  min_samples_leaf  l2_regularization  max_iter  val_accuracy  val_auc  val_log_loss\n",
      "          0.05          6              40                10               0.01       500      0.809507 0.909726      0.361732\n",
      "          0.05          6              40                10               0.01       400      0.809507 0.909726      0.361732\n",
      "          0.05          6              40                10               0.01       300      0.809507 0.909726      0.361732\n",
      "          0.05          6              40                50               0.01       500      0.807024 0.909432      0.362359\n",
      "          0.05          6              40                50               0.01       400      0.807024 0.909432      0.362359\n",
      "          0.05          6              40                10               0.00       400      0.807201 0.909408      0.361978\n",
      "          0.05          6              40                10               0.00       500      0.807201 0.909408      0.361978\n",
      "          0.08          5              40                50               0.10       500      0.805960 0.909406      0.362817\n",
      "          0.08          5              40                50               0.10       300      0.805960 0.909406      0.362817\n",
      "          0.08          5              40                50               0.10       400      0.805960 0.909406      0.362817\n"
     ]
    }
   ],
   "source": [
    "# ═══════════════════════════════════════════\n",
    "# CELL 10 — EXPANDED GRID SEARCH\n",
    "# Original search: 48 combos, fixed max_iter=300, l2 only [0.0, 0.1]\n",
    "# This search: 300 combos, broader ranges on all params\n",
    "# ═══════════════════════════════════════════\n",
    "param_grid = {\n",
    "    'learning_rate':     [0.03, 0.05, 0.08, 0.10, 0.12],\n",
    "    'max_depth':         [3, 4, 5, 6],\n",
    "    'max_leaf_nodes':    [15, 20, 31, 40],\n",
    "    'min_samples_leaf':  [10, 20, 30, 50],\n",
    "    'l2_regularization': [0.0, 0.01, 0.1, 0.5],\n",
    "    'max_iter':          [300, 400, 500],\n",
    "}\n",
    "\n",
    "grid = list(ParameterGrid(param_grid))\n",
    "print(f\"Total combinations: {len(grid)}\")\n",
    "\n",
    "tuning_rows = []\n",
    "for i, params in enumerate(grid):\n",
    "    model = HistGradientBoostingClassifier(random_state=42, **params)\n",
    "    model.fit(X_train, y_train)\n",
    "    val_proba = model.predict_proba(X_val)[:, 1]\n",
    "    val_pred  = (val_proba >= 0.5).astype(int)\n",
    "    tuning_rows.append({\n",
    "        **params,\n",
    "        'val_accuracy': accuracy_score(y_val, val_pred),\n",
    "        'val_auc':      roc_auc_score(y_val, val_proba),\n",
    "        'val_log_loss': log_loss(y_val, val_proba),\n",
    "    })\n",
    "    if (i+1) % 50 == 0:\n",
    "        best_so_far = max(tuning_rows, key=lambda x: x['val_auc'])\n",
    "        print(f\"  {i+1}/{len(grid)} done — best AUC so far: {best_so_far['val_auc']:.5f}\")\n",
    "\n",
    "tuning_df = pd.DataFrame(tuning_rows).sort_values('val_auc', ascending=False).reset_index(drop=True)\n",
    "\n",
    "print(\"\\nTop 10 configurations by val AUC:\")\n",
    "print(tuning_df.head(10)[['learning_rate','max_depth','max_leaf_nodes',\n",
    "                           'min_samples_leaf','l2_regularization','max_iter',\n",
    "                           'val_accuracy','val_auc','val_log_loss']].to_string(index=False))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "19f9fc4d",
   "metadata": {},
   "source": [
    "## Step 7 — Fit & Evaluate Best Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "e2a44faf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best params found:\n",
      "{'learning_rate': 0.05, 'max_depth': 6, 'max_leaf_nodes': 40, 'min_samples_leaf': 10, 'l2_regularization': 0.01, 'max_iter': 500}\n",
      "\n",
      "Comparison (original vs new tuned):\n",
      "           set  accuracy      auc  log_loss\n",
      "  val_ORIGINAL  0.804718 0.908220  0.365056\n",
      " val_NEW_TUNED  0.809507 0.909726  0.361732\n",
      " test_ORIGINAL  0.802740 0.903801  0.373176\n",
      "test_NEW_TUNED  0.801056 0.904312  0.371751\n"
     ]
    }
   ],
   "source": [
    "# ═══════════════════════════════════════════\n",
    "# CELL 11 — FIT BEST MODEL & COMPARE TO BASELINE\n",
    "# ═══════════════════════════════════════════\n",
    "param_cols = ['learning_rate','max_depth','max_leaf_nodes',\n",
    "              'min_samples_leaf','l2_regularization','max_iter']\n",
    "\n",
    "best_params = tuning_df.loc[0, param_cols].to_dict()\n",
    "for k in ['max_depth','max_leaf_nodes','min_samples_leaf','max_iter']:\n",
    "    if best_params[k] is not None:\n",
    "        best_params[k] = int(best_params[k])\n",
    "for k in ['learning_rate','l2_regularization']:\n",
    "    best_params[k] = float(best_params[k])\n",
    "\n",
    "print(\"Best params found:\")\n",
    "print(best_params)\n",
    "\n",
    "best_tuned_hgb = HistGradientBoostingClassifier(random_state=42, **best_params)\n",
    "best_tuned_hgb.fit(X_train, y_train)\n",
    "\n",
    "comparison = pd.DataFrame([\n",
    "    evaluate_binary_model(baseline_hgb,   X_val,  y_val,  'val_ORIGINAL'),\n",
    "    evaluate_binary_model(best_tuned_hgb, X_val,  y_val,  'val_NEW_TUNED'),\n",
    "    evaluate_binary_model(baseline_hgb,   X_test, y_test, 'test_ORIGINAL'),\n",
    "    evaluate_binary_model(best_tuned_hgb, X_test, y_test, 'test_NEW_TUNED'),\n",
    "])\n",
    "print(\"\\nComparison (original vs new tuned):\")\n",
    "print(comparison[['set','accuracy','auc','log_loss']].to_string(index=False))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "78bbe87e",
   "metadata": {},
   "source": [
    "## Step 8 — Save Model (only if test AUC improved)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "7cec9aea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Old test AUC: 0.90380\n",
      "New test AUC: 0.90431\n",
      "Improvement:  +0.00051\n",
      "\n",
      "✅ Saved new model — it's better!\n",
      "Best params: {'learning_rate': 0.05, 'max_depth': 6, 'max_leaf_nodes': 40, 'min_samples_leaf': 10, 'l2_regularization': 0.01, 'max_iter': 500}\n"
     ]
    }
   ],
   "source": [
    "# ═══════════════════════════════════════════\n",
    "# CELL 12 — SAVE NEW MODEL\n",
    "# Only run this if test AUC in cell 11 is >= 0.910\n",
    "# ═══════════════════════════════════════════\n",
    "old_test_auc = evaluate_binary_model(baseline_hgb, X_test, y_test, 'old')['auc']\n",
    "new_test_auc = evaluate_binary_model(best_tuned_hgb, X_test, y_test, 'new')['auc']\n",
    "\n",
    "print(f\"Old test AUC: {old_test_auc:.5f}\")\n",
    "print(f\"New test AUC: {new_test_auc:.5f}\")\n",
    "print(f\"Improvement:  {new_test_auc - old_test_auc:+.5f}\")\n",
    "\n",
    "if new_test_auc >= old_test_auc:\n",
    "    joblib.dump(best_tuned_hgb, '../model/tennis_model_v2.pkl')\n",
    "    with open('../model/feature_cols.json', 'w') as f:\n",
    "        json.dump(feature_cols, f)\n",
    "    print(\"\\n✅ Saved new model — it's better!\")\n",
    "    print(f\"Best params: {best_params}\")\n",
    "else:\n",
    "    print(\"\\n⚠️  New model did not improve on test set — keeping original.\")\n",
    "    print(\"Original params were already optimal.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "66fb5712-a61a-4503-a779-36de2ee688e5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'learning_rate': 0.05, 'max_depth': 6, 'max_leaf_nodes': 40, 'min_samples_leaf': 10, 'l2_regularization': 0.01, 'max_iter': 500}\n"
     ]
    }
   ],
   "source": [
    "print(best_params)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "46db38c7-3d80-4658-9ba2-a7e2d0dfcff9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Test rows with 3+ H2H meetings: 1928 / 13064 (14.8%)\n",
      "\n",
      "H2H win rate distribution (3+ meetings):\n",
      "         p1_h2h_wr     p1_h2h_n\n",
      "count  6416.000000  6416.000000\n",
      "mean      0.500000     4.435162\n",
      "std       0.205179     2.065378\n",
      "min       0.066667     3.000000\n",
      "25%       0.333333     3.000000\n",
      "50%       0.500000     4.000000\n",
      "75%       0.666667     5.000000\n",
      "max       0.933333    21.000000\n",
      "\n",
      "Test rows with 5+ H2H meetings: 752 / 13064 (5.8%)\n",
      "These are the matches where recency weighting would have the most impact\n"
     ]
    }
   ],
   "source": [
    "# How many test set matches have meaningful H2H history (>= 3 meetings)?\n",
    "test_with_h2h = test_df[test_df['p1_h2h_n'] >= 3]\n",
    "print(f\"Test rows with 3+ H2H meetings: {len(test_with_h2h)} / {len(test_df)} ({len(test_with_h2h)/len(test_df):.1%})\")\n",
    "\n",
    "# How different is the decayed vs raw H2H on those rows?\n",
    "# Use current model_df_v2 h2h values\n",
    "h2h_check = model_df_v2[model_df_v2['p1_h2h_n'] >= 3][['p1_h2h_wr', 'p1_h2h_n']].describe()\n",
    "print(\"\\nH2H win rate distribution (3+ meetings):\")\n",
    "print(h2h_check)\n",
    "\n",
    "# What % of test matches are between players who've met 5+ times?\n",
    "deep_h2h = test_df[test_df['p1_h2h_n'] >= 5]\n",
    "print(f\"\\nTest rows with 5+ H2H meetings: {len(deep_h2h)} / {len(test_df)} ({len(deep_h2h)/len(test_df):.1%})\")\n",
    "print(f\"These are the matches where recency weighting would have the most impact\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6b02a3de-11f2-40ac-951b-d8aac381be6d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model loaded: <class 'sklearn.ensemble._hist_gradient_boosting.gradient_boosting.HistGradientBoostingClassifier'>\n",
      "Features: 47\n"
     ]
    }
   ],
   "source": [
    "# ── FETCH UPDATED STATS FROM CURRENT SAVED MODEL ──────────────────────────\n",
    "import joblib, json\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.metrics import accuracy_score, roc_auc_score, log_loss, brier_score_loss, confusion_matrix\n",
    "\n",
    "# Load the saved model and feature cols\n",
    "best_tuned_hgb = joblib.load('../model/tennis_model_v2.pkl')\n",
    "feature_cols   = json.load(open('../model/feature_cols.json'))\n",
    "\n",
    "print(\"Model loaded:\", type(best_tuned_hgb))\n",
    "print(\"Features:\", len(feature_cols))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "b7139aea-e4c8-48cf-ab1a-fb02b7c5cb37",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=== MODEL PERFORMANCE ===\n",
      "Train: acc=0.84889  auc=0.94073  log_loss=0.31104\n",
      "Val: acc=0.80951  auc=0.90973  log_loss=0.36173\n",
      "Test: acc=0.80106  auc=0.90431  log_loss=0.37175\n",
      "\n",
      "Confusion Matrix (Test):\n",
      "  TN=5210  FP=1322\n",
      "  FN=1277  TP=5255\n",
      "\n",
      "=== ACCURACY BY SURFACE ===\n",
      "Clay: 0.80000 (n=3710)\n",
      "Grass: 0.85058 (n=1198)\n",
      "Hard: 0.79426 (n=8156)\n",
      "\n",
      "=== ACCURACY BY TOURNAMENT LEVEL ===\n",
      "250: 0.79410 (n=4104)\n",
      "500: 0.83641 (n=2164)\n",
      "ATP: 0.79321 (n=324)\n",
      "Finals: 0.88333 (n=60)\n",
      "Grand Slam: 0.85470 (n=2168)\n",
      "Masters: 0.77997 (n=3186)\n",
      "Other: 0.70699 (n=1058)\n"
     ]
    }
   ],
   "source": [
    "# ── PERFORMANCE BY SPLIT ──────────────────────────────────────────────────\n",
    "print(\"=== MODEL PERFORMANCE ===\")\n",
    "for name, X, y in [(\"Train\", X_train, y_train), (\"Val\", X_val, y_val), (\"Test\", X_test, y_test)]:\n",
    "    proba = best_tuned_hgb.predict_proba(X)[:,1]\n",
    "    pred  = (proba >= 0.5).astype(int)\n",
    "    print(f\"{name}: acc={accuracy_score(y,pred):.5f}  auc={roc_auc_score(y,proba):.5f}  log_loss={log_loss(y,proba):.5f}\")\n",
    "\n",
    "# ── CONFUSION MATRIX ──────────────────────────────────────────────────────\n",
    "proba_test = best_tuned_hgb.predict_proba(X_test)[:,1]\n",
    "pred_test  = (proba_test >= 0.5).astype(int)\n",
    "cm = confusion_matrix(y_test, pred_test)\n",
    "print(f\"\\nConfusion Matrix (Test):\")\n",
    "print(f\"  TN={cm[0,0]}  FP={cm[0,1]}\")\n",
    "print(f\"  FN={cm[1,0]}  TP={cm[1,1]}\")\n",
    "\n",
    "# ── BY SURFACE ────────────────────────────────────────────────────────────\n",
    "surface_map_rev = {0:'Hard', 1:'Clay', 2:'Grass'}\n",
    "test_df['surface_name'] = test_df['surface'].map(surface_map_rev)\n",
    "print(\"\\n=== ACCURACY BY SURFACE ===\")\n",
    "for surf, grp in test_df.groupby('surface_name'):\n",
    "    acc = accuracy_score(grp['target'], best_tuned_hgb.predict(grp[feature_cols]))\n",
    "    print(f\"{surf}: {acc:.5f} (n={len(grp)})\")\n",
    "\n",
    "# ── BY TOURNAMENT LEVEL ───────────────────────────────────────────────────\n",
    "level_map_rev = {0:'250', 1:'500', 2:'ATP', 3:'Masters', 4:'Grand Slam', 5:'Other', 6:'Finals'}\n",
    "test_df['level_name'] = test_df['level'].map(level_map_rev)\n",
    "print(\"\\n=== ACCURACY BY TOURNAMENT LEVEL ===\")\n",
    "for level, grp in test_df.groupby('level_name'):\n",
    "    if len(grp) < 50: continue\n",
    "    acc = accuracy_score(grp['target'], best_tuned_hgb.predict(grp[feature_cols]))\n",
    "    print(f\"{level}: {acc:.5f} (n={len(grp)})\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "4e7dd631-9741-4f6a-93c6-5a60dee461a7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=== TOP 10 MOST CONFIDENT WRONG PREDICTIONS ===\n",
      "match_date               p1_name            p2_name surface_name  p1_win_prob  confidence\n",
      "2024-03-04            Luca Nardi      Zhizhen Zhang         Hard     0.036032    0.963968\n",
      "2024-05-06      Alejandro Tabilo     Novak Djokovic         Clay     0.037204    0.962796\n",
      "2024-01-15         Jannik Sinner    Daniil Medvedev         Hard     0.043444    0.956556\n",
      "2024-09-20        Frances Tiafoe    Daniil Medvedev         Hard     0.045672    0.954328\n",
      "2024-10-28         Arthur Cazaux        Ben Shelton         Hard     0.047503    0.952497\n",
      "2025-11-10 Felix Auger-Aliassime   Alexander Zverev         Hard     0.048517    0.951483\n",
      "2024-10-28      Alexander Zverev Stefanos Tsitsipas         Hard     0.053246    0.946754\n",
      "2024-08-18       Roman Safiullin    Corentin Moutet         Hard     0.057608    0.942392\n",
      "2025-02-24    Stefanos Tsitsipas    Karen Khachanov         Hard     0.060424    0.939576\n",
      "2024-08-06           Nuno Borges        Ugo Humbert         Hard     0.065372    0.934628\n",
      "\n",
      "=== HIGH CONFIDENCE ACCURACY BY SURFACE ===\n",
      "Hard: 107926 predictions >80%, actual win rate: 0.940\n",
      "Clay: 940 predictions >80%, actual win rate: 0.976\n",
      "Grass: 370 predictions >80%, actual win rate: 0.981\n"
     ]
    }
   ],
   "source": [
    "# ── WRONG PREDICTIONS ─────────────────────────────────────────────────────\n",
    "# Join names back\n",
    "name_lookup = df[['match_id','winner_name','loser_name','winner_id','loser_id']].drop_duplicates()\n",
    "test_named  = test_df.merge(name_lookup, on='match_id', how='left')\n",
    "test_named['p1_name'] = test_named.apply(lambda r: r['winner_name'] if r['target']==1 else r['loser_name'], axis=1)\n",
    "test_named['p2_name'] = test_named.apply(lambda r: r['loser_name']  if r['target']==1 else r['winner_name'], axis=1)\n",
    "test_named['p1_win_prob'] = best_tuned_hgb.predict_proba(test_named[feature_cols])[:,1]\n",
    "\n",
    "# Deduplicate (one row per match, winner perspective)\n",
    "test_clean = test_named[test_named['target']==1].copy()\n",
    "\n",
    "wrong = test_clean[test_clean['p1_win_prob'] < 0.5].copy()\n",
    "wrong['confidence'] = 1 - wrong['p1_win_prob']\n",
    "wrong = wrong.sort_values('confidence', ascending=False)\n",
    "\n",
    "print(\"=== TOP 10 MOST CONFIDENT WRONG PREDICTIONS ===\")\n",
    "print(wrong[['match_date','p1_name','p2_name','surface_name','p1_win_prob','confidence']].head(10).to_string(index=False))\n",
    "\n",
    "# ── CALIBRATION ───────────────────────────────────────────────────────────\n",
    "print(\"\\n=== HIGH CONFIDENCE ACCURACY BY SURFACE ===\")\n",
    "for surf in ['Hard','Clay','Grass']:\n",
    "    grp = test_named[test_named['surface_name']==surf]\n",
    "    high = grp[grp['p1_win_prob'] > 0.80]\n",
    "    print(f\"{surf}: {len(high)} predictions >80%, actual win rate: {high['target'].mean():.3f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "c6b4b855-0ffe-4e46-8637-ff0eda078321",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=== CLASSIFICATION REPORT ===\n",
      "                precision    recall  f1-score   support\n",
      "\n",
      "Predicted Loss       0.80      0.80      0.80      6532\n",
      " Predicted Win       0.80      0.80      0.80      6532\n",
      "\n",
      "      accuracy                           0.80     13064\n",
      "     macro avg       0.80      0.80      0.80     13064\n",
      "  weighted avg       0.80      0.80      0.80     13064\n",
      "\n",
      "\n",
      "=== CALIBRATION CURVE DATA ===\n",
      "  predicted=0.024  actual=0.009\n",
      "  predicted=0.151  actual=0.166\n",
      "  predicted=0.251  actual=0.269\n",
      "  predicted=0.351  actual=0.383\n",
      "  predicted=0.453  actual=0.450\n",
      "  predicted=0.548  actual=0.540\n",
      "  predicted=0.650  actual=0.617\n",
      "  predicted=0.747  actual=0.719\n",
      "  predicted=0.850  actual=0.845\n",
      "  predicted=0.976  actual=0.990\n",
      "\n",
      "=== ACCURACY BY YEAR (TEST SET) ===\n",
      "2024: 0.81286 (n=5974)\n",
      "2025: 0.80004 (n=5346)\n",
      "2026: 0.76376 (n=1744)\n",
      "\n",
      "=== ROC CURVE SAMPLE POINTS ===\n",
      "  fpr=0.000  tpr=0.000  threshold=inf\n",
      "  fpr=0.029  tpr=0.541  threshold=0.767\n",
      "  fpr=0.064  tpr=0.621  threshold=0.687\n",
      "  fpr=0.107  tpr=0.693  threshold=0.613\n",
      "  fpr=0.154  tpr=0.749  threshold=0.553\n",
      "  fpr=0.200  tpr=0.802  threshold=0.503\n",
      "  fpr=0.247  tpr=0.850  threshold=0.456\n",
      "  fpr=0.309  tpr=0.891  threshold=0.393\n",
      "  fpr=0.376  tpr=0.931  threshold=0.322\n",
      "  fpr=0.457  tpr=0.970  threshold=0.234\n",
      "  fpr=1.000  tpr=1.000  threshold=0.000\n",
      "\n",
      "=== PROBABILITY DISTRIBUTION ===\n",
      "Winners — mean prob: 0.748  median: 0.811\n",
      "Losers  — mean prob: 0.255  median: 0.191\n"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import (precision_score, recall_score, f1_score,\n",
    "                              classification_report, roc_curve)\n",
    "from sklearn.calibration import calibration_curve\n",
    "import pandas as pd\n",
    "\n",
    "proba_test = best_tuned_hgb.predict_proba(X_test)[:,1]\n",
    "pred_test  = (proba_test >= 0.5).astype(int)\n",
    "\n",
    "# ── FULL CLASSIFICATION REPORT ──────────────────────────────────────────\n",
    "print(\"=== CLASSIFICATION REPORT ===\")\n",
    "print(classification_report(y_test, pred_test, target_names=['Predicted Loss','Predicted Win']))\n",
    "\n",
    "# ── CALIBRATION CURVE (real values) ──────────────────────────────────────\n",
    "prob_true, prob_pred = calibration_curve(y_test, proba_test, n_bins=10)\n",
    "print(\"\\n=== CALIBRATION CURVE DATA ===\")\n",
    "for pt, pp in zip(prob_true, prob_pred):\n",
    "    print(f\"  predicted={pp:.3f}  actual={pt:.3f}\")\n",
    "\n",
    "# ── ACCURACY BY YEAR ───────────────────────────────────────────────────\n",
    "print(\"\\n=== ACCURACY BY YEAR (TEST SET) ===\")\n",
    "test_df['pred_prob'] = best_tuned_hgb.predict_proba(X_test)[:,1]\n",
    "test_df['predicted'] = (test_df['pred_prob'] >= 0.5).astype(int)\n",
    "for year, grp in test_df.groupby('year'):\n",
    "    acc = accuracy_score(grp['target'], grp['predicted'])\n",
    "    n   = len(grp)\n",
    "    print(f\"{year}: {acc:.5f} (n={n})\")\n",
    "\n",
    "# ── ROC CURVE DATA ────────────────────────────────────────────────────\n",
    "fpr, tpr, thresholds = roc_curve(y_test, proba_test)\n",
    "# Sample 10 evenly spaced points for the report\n",
    "idx = [int(i * len(fpr)/10) for i in range(10)] + [-1]\n",
    "print(\"\\n=== ROC CURVE SAMPLE POINTS ===\")\n",
    "for i in idx:\n",
    "    print(f\"  fpr={fpr[i]:.3f}  tpr={tpr[i]:.3f}  threshold={thresholds[i]:.3f}\")\n",
    "\n",
    "# ── PROBABILITY DISTRIBUTION ──────────────────────────────────────────\n",
    "wins  = proba_test[y_test == 1]\n",
    "loses = proba_test[y_test == 0]\n",
    "print(f\"\\n=== PROBABILITY DISTRIBUTION ===\")\n",
    "print(f\"Winners — mean prob: {wins.mean():.3f}  median: {wins.median() if hasattr(wins,'median') else pd.Series(wins).median():.3f}\")\n",
    "print(f\"Losers  — mean prob: {loses.mean():.3f}  median: {loses.median() if hasattr(loses,'median') else pd.Series(loses).median():.3f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "a3df5d4c-6b36-4860-9a89-dd1800f44baa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "K=  4: val_auc=0.90824  test_auc=0.90350\n",
      "K=  8: val_auc=0.90947  test_auc=0.90363\n",
      "K= 12: val_auc=0.90931  test_auc=0.90111\n",
      "K= 16: val_auc=0.90952  test_auc=0.90053\n"
     ]
    }
   ],
   "source": [
    "for k in [4, 8, 12, 16]:\n",
    "    elo_df = compute_elos_with_k(df, k)\n",
    "    elo_lookup = elo_df.drop_duplicates('match_id').set_index('match_id')\n",
    "    temp_df = model_df_v2.copy()\n",
    "    \n",
    "    for mask, we_col, le_col in [\n",
    "        (temp_df['target']==1, 'w_elo', 'l_elo'),\n",
    "        (temp_df['target']==0, 'l_elo', 'w_elo')\n",
    "    ]:\n",
    "        mids = temp_df.loc[mask, 'match_id']\n",
    "        temp_df.loc[mask, 'p1_elo']         = mids.map(elo_lookup[we_col]).values\n",
    "        temp_df.loc[mask, 'p2_elo']         = mids.map(elo_lookup[le_col]).values\n",
    "        wse = 'w_surface_elo' if we_col == 'w_elo' else 'l_surface_elo'\n",
    "        lse = 'l_surface_elo' if we_col == 'w_elo' else 'w_surface_elo'\n",
    "        temp_df.loc[mask, 'p1_surface_elo'] = mids.map(elo_lookup[wse]).values\n",
    "        temp_df.loc[mask, 'p2_surface_elo'] = mids.map(elo_lookup[lse]).values\n",
    "        temp_df.loc[mask, 'elo_diff']         = temp_df.loc[mask,'p1_elo'] - temp_df.loc[mask,'p2_elo']\n",
    "        temp_df.loc[mask, 'surface_elo_diff'] = temp_df.loc[mask,'p1_surface_elo'] - temp_df.loc[mask,'p2_surface_elo']\n",
    "    \n",
    "    tr = temp_df[temp_df['match_date'] < '2023-01-01']\n",
    "    va = temp_df[(temp_df['match_date'] >= '2023-01-01') & (temp_df['match_date'] < '2024-01-01')]\n",
    "    te = temp_df[temp_df['match_date'] >= '2024-01-01']\n",
    "    \n",
    "    model = HistGradientBoostingClassifier(random_state=42,\n",
    "        learning_rate=0.05, max_depth=6, max_leaf_nodes=40,\n",
    "        min_samples_leaf=10, l2_regularization=0.01, max_iter=500)\n",
    "    model.fit(tr[feature_cols], tr['target'])\n",
    "    \n",
    "    val_auc  = roc_auc_score(va['target'], model.predict_proba(va[feature_cols])[:,1])\n",
    "    test_auc = roc_auc_score(te['target'], model.predict_proba(te[feature_cols])[:,1])\n",
    "    print(f\"K={k:3d}: val_auc={val_auc:.5f}  test_auc={test_auc:.5f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "bbc4aa36-00f4-44a2-acaa-4d8e3a3e75c2",
   "metadata": {},
   "outputs": [],
   "source": [
    "def predict_matchup(p1_name, p2_name, surface='Hard', level='G', round_='F', best_of=5):\n",
    "    SURFACE_MAP = {'Hard':0,'Clay':1,'Grass':2,'Carpet':0}\n",
    "    LEVEL_MAP   = {'250':0,'500':1,'A':2,'M':3,'G':4,'D':5,'O':5,'F':6}\n",
    "    ROUND_MAP   = {'R128':1,'R64':2,'R32':3,'R16':4,'QF':5,'SF':6,'F':7,'RR':3}\n",
    "\n",
    "    surf_enc  = SURFACE_MAP.get(surface, 0)\n",
    "    level_enc = LEVEL_MAP.get(level, 4)\n",
    "    round_enc = ROUND_MAP.get(round_, 7)\n",
    "\n",
    "    def find_pid(name):\n",
    "        last = name.split()[-1]\n",
    "        w = df[df['winner_name'].str.contains(last, na=False)].sort_values('tourney_date')\n",
    "        l = df[df['loser_name'].str.contains(last, na=False)].sort_values('tourney_date')\n",
    "        if len(w) == 0 and len(l) == 0:\n",
    "            return None\n",
    "        if len(w) == 0: return l.iloc[-1]['loser_id']\n",
    "        if len(l) == 0: return w.iloc[-1]['winner_id']\n",
    "        if w.iloc[-1]['tourney_date'] >= l.iloc[-1]['tourney_date']:\n",
    "            return w.iloc[-1]['winner_id']\n",
    "        return l.iloc[-1]['loser_id']\n",
    "\n",
    "    def get_last_features(pid):\n",
    "        # Find all rows in feature_df where this player appeared\n",
    "        w_rows = feature_df[feature_df['match_id'].isin(\n",
    "            df[df['winner_id']==pid]['match_id'])].copy()\n",
    "        w_rows['_w'] = True\n",
    "        l_rows = feature_df[feature_df['match_id'].isin(\n",
    "            df[df['loser_id']==pid]['match_id'])].copy()\n",
    "        l_rows['_w'] = False\n",
    "        \n",
    "        all_rows = pd.concat([w_rows, l_rows]).sort_values('match_date')\n",
    "        if len(all_rows) == 0:\n",
    "            return None\n",
    "        r = all_rows.iloc[-1]\n",
    "        w = r['_w']\n",
    "        \n",
    "        # Also get rank/age from df\n",
    "        df_row = df[df['match_id']==r['match_id']].iloc[0]\n",
    "        rank   = df_row['winner_rank']        if w else df_row['loser_rank']\n",
    "        rpts   = df_row['winner_rank_points'] if w else df_row['loser_rank_points']\n",
    "        age    = df_row['winner_age']         if w else df_row['loser_age']\n",
    "        \n",
    "        return {\n",
    "            'recent_wr':   r['w_recent_wr']   if w else r['l_recent_wr'],\n",
    "            'recent_n':    r['w_recent_n']    if w else r['l_recent_n'],\n",
    "            'surface_wr':  r['w_surface_wr']  if w else r['l_surface_wr'],\n",
    "            'surface_n':   r['w_surface_n']   if w else r['l_surface_n'],\n",
    "            'days_rest':   r['w_days_rest']   if w else r['l_days_rest'],\n",
    "            'matches_7d':  r['w_matches_7d']  if w else r['l_matches_7d'],\n",
    "            'matches_30d': r['w_matches_30d'] if w else r['l_matches_30d'],\n",
    "            'elo':         r['w_elo']         if w else r['l_elo'],\n",
    "            'surface_elo': r['w_surface_elo'] if w else r['l_surface_elo'],\n",
    "            'rank': rank, 'rank_points': rpts, 'age': age,\n",
    "        }\n",
    "\n",
    "    p1_id = find_pid(p1_name)\n",
    "    p2_id = find_pid(p2_name)\n",
    "    if not p1_id or not p2_id:\n",
    "        print(f\"Player not found: {p1_name if not p1_id else p2_name}\"); return\n",
    "\n",
    "    f1 = get_last_features(p1_id)\n",
    "    f2 = get_last_features(p2_id)\n",
    "    if not f1 or not f2:\n",
    "        print(\"Could not extract features\"); return\n",
    "\n",
    "    # H2H\n",
    "    h2h = df[((df['winner_id']==p1_id)&(df['loser_id']==p2_id))|\n",
    "              ((df['winner_id']==p2_id)&(df['loser_id']==p1_id))]\n",
    "    p1_wins   = (h2h['winner_id']==p1_id).sum()\n",
    "    total_h2h = len(h2h)\n",
    "    p1_h2h_wr = (p1_wins+1)/(total_h2h+2)\n",
    "\n",
    "    h2h_s       = h2h[h2h['surface_enc']==surf_enc]\n",
    "    p1_s_wins   = (h2h_s['winner_id']==p1_id).sum()\n",
    "    total_h2h_s = len(h2h_s)\n",
    "    p1_h2h_s_wr = (p1_s_wins+1)/(total_h2h_s+2)\n",
    "\n",
    "    row = {\n",
    "        'p1_rank': f1['rank'], 'p2_rank': f2['rank'],\n",
    "        'rank_diff': f2['rank']-f1['rank'],\n",
    "        'p1_rank_points': f1['rank_points'], 'p2_rank_points': f2['rank_points'],\n",
    "        'rank_points_diff': f1['rank_points']-f2['rank_points'],\n",
    "        'p1_age': f1['age'], 'p2_age': f2['age'], 'age_diff': f1['age']-f2['age'],\n",
    "        'surface': surf_enc, 'level': level_enc, 'indoor': 0,\n",
    "        'round': round_enc, 'best_of': best_of,\n",
    "        'p1_recent_wr': f1['recent_wr'], 'p2_recent_wr': f2['recent_wr'],\n",
    "        'recent_wr_diff': f1['recent_wr']-f2['recent_wr'],\n",
    "        'p1_recent_n': f1['recent_n'], 'p2_recent_n': f2['recent_n'],\n",
    "        'p1_surface_wr': f1['surface_wr'], 'p2_surface_wr': f2['surface_wr'],\n",
    "        'surface_wr_diff': f1['surface_wr']-f2['surface_wr'],\n",
    "        'p1_surface_n': f1['surface_n'], 'p2_surface_n': f2['surface_n'],\n",
    "        'p1_h2h_wr': p1_h2h_wr, 'p2_h2h_wr': 1-p1_h2h_wr,\n",
    "        'h2h_diff': p1_h2h_wr-(1-p1_h2h_wr), 'p1_h2h_n': total_h2h,\n",
    "        'p1_h2h_surface_wr': p1_h2h_s_wr, 'p2_h2h_surface_wr': 1-p1_h2h_s_wr,\n",
    "        'h2h_surface_diff': p1_h2h_s_wr-(1-p1_h2h_s_wr), 'p1_h2h_surface_n': total_h2h_s,\n",
    "        'p1_days_rest': f1['days_rest'], 'p2_days_rest': f2['days_rest'],\n",
    "        'rest_diff': f1['days_rest']-f2['days_rest'],\n",
    "        'p1_matches_7d': f1['matches_7d'], 'p2_matches_7d': f2['matches_7d'],\n",
    "        'matches_7d_diff': f1['matches_7d']-f2['matches_7d'],\n",
    "        'p1_matches_30d': f1['matches_30d'], 'p2_matches_30d': f2['matches_30d'],\n",
    "        'matches_30d_diff': f1['matches_30d']-f2['matches_30d'],\n",
    "        'p1_elo': f1['elo'], 'p2_elo': f2['elo'],\n",
    "        'elo_diff': f1['elo']-f2['elo'],\n",
    "        'p1_surface_elo': f1['surface_elo'], 'p2_surface_elo': f2['surface_elo'],\n",
    "        'surface_elo_diff': f1['surface_elo']-f2['surface_elo'],\n",
    "    }\n",
    "\n",
    "    X = pd.DataFrame([row])[feature_cols]\n",
    "    prob = model.predict_proba(X)[0]\n",
    "    p1_prob, p2_prob = prob[1], prob[0]\n",
    "    winner = p1_name if p1_prob > 0.5 else p2_name\n",
    "    conf   = max(p1_prob, p2_prob)\n",
    "    flag   = \" ⚠️  SUSPICIOUS\" if conf > 0.90 else \"\"\n",
    "\n",
    "    print(f\"\\n{'─'*60}\")\n",
    "    print(f\"{p1_name} vs {p2_name} | {surface} | {level} {round_}\")\n",
    "    print(f\"  {p1_name:<25} {p1_prob:.1%}\")\n",
    "    print(f\"  {p2_name:<25} {p2_prob:.1%}\")\n",
    "    print(f\"  → {winner} wins ({conf:.1%} confidence){flag}\")\n",
    "    print(f\"  H2H: {p1_wins}–{total_h2h-p1_wins} overall | {p1_s_wins}–{total_h2h_s-p1_s_wins} on {surface}\")\n",
    "    print(f\"  ELO: {f1['elo']:.0f} vs {f2['elo']:.0f} | Surface ELO: {f1['surface_elo']:.0f} vs {f2['surface_elo']:.0f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "2239c7bd-abc0-4a15-9173-921bbfd00fe6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Carlos Alcaraz vs Jannik Sinner | Hard | G F\n",
      "  Carlos Alcaraz            57.8%\n",
      "  Jannik Sinner             42.2%\n",
      "  → Carlos Alcaraz wins (57.8% confidence)\n",
      "  H2H: 9–6 overall | 6–3 on Hard\n",
      "  ELO: 2179 vs 2240 | Surface ELO: 2076 vs 2221\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Carlos Alcaraz vs Jannik Sinner | Clay | G F\n",
      "  Carlos Alcaraz            93.1%\n",
      "  Jannik Sinner             6.9%\n",
      "  → Carlos Alcaraz wins (93.1% confidence) ⚠️  SUSPICIOUS\n",
      "  H2H: 9–6 overall | 3–1 on Clay\n",
      "  ELO: 2179 vs 2240 | Surface ELO: 2076 vs 2221\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Carlos Alcaraz vs Jannik Sinner | Grass | G F\n",
      "  Carlos Alcaraz            63.3%\n",
      "  Jannik Sinner             36.7%\n",
      "  → Carlos Alcaraz wins (63.3% confidence)\n",
      "  H2H: 9–6 overall | 0–2 on Grass\n",
      "  ELO: 2179 vs 2240 | Surface ELO: 2076 vs 2221\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Novak Djokovic vs Carlos Alcaraz | Hard | G F\n",
      "  Novak Djokovic            11.5%\n",
      "  Carlos Alcaraz            88.5%\n",
      "  → Carlos Alcaraz wins (88.5% confidence)\n",
      "  H2H: 5–5 overall | 3–2 on Hard\n",
      "  ELO: 2053 vs 2179 | Surface ELO: 2023 vs 2076\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Novak Djokovic vs Carlos Alcaraz | Clay | G F\n",
      "  Novak Djokovic            11.5%\n",
      "  Carlos Alcaraz            88.5%\n",
      "  → Carlos Alcaraz wins (88.5% confidence)\n",
      "  H2H: 5–5 overall | 2–1 on Clay\n",
      "  ELO: 2053 vs 2179 | Surface ELO: 2023 vs 2076\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Novak Djokovic vs Jannik Sinner | Hard | G F\n",
      "  Novak Djokovic            7.3%\n",
      "  Jannik Sinner             92.7%\n",
      "  → Jannik Sinner wins (92.7% confidence) ⚠️  SUSPICIOUS\n",
      "  H2H: 5–6 overall | 2–4 on Hard\n",
      "  ELO: 2053 vs 2240 | Surface ELO: 2023 vs 2221\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Alexander Zverev vs Carlos Alcaraz | Clay | G F\n",
      "  Alexander Zverev          96.9%\n",
      "  Carlos Alcaraz            3.1%\n",
      "  → Alexander Zverev wins (96.9% confidence) ⚠️  SUSPICIOUS\n",
      "  H2H: 6–7 overall | 1–3 on Clay\n",
      "  ELO: 1940 vs 2179 | Surface ELO: 1911 vs 2076\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Daniil Medvedev vs Jannik Sinner | Hard | G F\n",
      "  Daniil Medvedev           9.6%\n",
      "  Jannik Sinner             90.4%\n",
      "  → Jannik Sinner wins (90.4% confidence) ⚠️  SUSPICIOUS\n",
      "  H2H: 7–9 overall | 6–9 on Hard\n",
      "  ELO: 1934 vs 2240 | Surface ELO: 1909 vs 2221\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Carlos Alcaraz vs Alexander Zverev | Clay | G F\n",
      "  Carlos Alcaraz            98.0%\n",
      "  Alexander Zverev          2.0%\n",
      "  → Carlos Alcaraz wins (98.0% confidence) ⚠️  SUSPICIOUS\n",
      "  H2H: 7–6 overall | 3–1 on Clay\n",
      "  ELO: 2179 vs 1940 | Surface ELO: 2076 vs 1911\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Jannik Sinner vs Daniil Medvedev | Hard | G F\n",
      "  Jannik Sinner             95.5%\n",
      "  Daniil Medvedev           4.5%\n",
      "  → Jannik Sinner wins (95.5% confidence) ⚠️  SUSPICIOUS\n",
      "  H2H: 9–7 overall | 9–6 on Hard\n",
      "  ELO: 2240 vs 1934 | Surface ELO: 2221 vs 1909\n"
     ]
    }
   ],
   "source": [
    "for args in matchups:\n",
    "    predict_matchup(*args)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "c6e01482-feea-44d5-b49d-49301bf38919",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Carlos Alcaraz vs Jannik Sinner | Hard | G F\n",
      "  Carlos Alcaraz               57.8%\n",
      "  Jannik Sinner                42.2%\n",
      "  → Carlos Alcaraz wins (57.8%)\n",
      "  H2H: 9–6 | 6–3 on Hard\n",
      "  ELO: 2179 vs 2240 | Surface: 2076 vs 2221\n",
      "  Rank: 1 vs 2 | Pts: 13550 vs 11400\n",
      "  Surface WR: 0.767 (n=10) vs 0.833 (n=10)\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Carlos Alcaraz vs Jannik Sinner | Clay | G F\n",
      "  Carlos Alcaraz               96.6%\n",
      "  Jannik Sinner                3.4%\n",
      "  → Carlos Alcaraz wins (96.6%) ⚠️  SUSPICIOUS\n",
      "  H2H: 9–6 | 3–1 on Clay\n",
      "  ELO: 2179 vs 2240 | Surface: 2016 vs 1891\n",
      "  Rank: 1 vs 2 | Pts: 13550 vs 11400\n",
      "  Surface WR: 0.767 (n=10) vs 0.700 (n=10)\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Carlos Alcaraz vs Jannik Sinner | Grass | G F\n",
      "  Carlos Alcaraz               70.3%\n",
      "  Jannik Sinner                29.7%\n",
      "  → Carlos Alcaraz wins (70.3%)\n",
      "  H2H: 9–6 | 0–2 on Grass\n",
      "  ELO: 2179 vs 2240 | Surface: 1829 vs 1755\n",
      "  Rank: 1 vs 2 | Pts: 13550 vs 11400\n",
      "  Surface WR: 0.767 (n=10) vs 0.700 (n=10)\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Novak Djokovic vs Carlos Alcaraz | Hard | G F\n",
      "  Novak Djokovic               11.5%\n",
      "  Carlos Alcaraz               88.5%\n",
      "  → Carlos Alcaraz wins (88.5%)\n",
      "  H2H: 5–5 | 3–2 on Hard\n",
      "  ELO: 2053 vs 2179 | Surface: 2023 vs 2076\n",
      "  Rank: 3 vs 1 | Pts: 5280 vs 13550\n",
      "  Surface WR: 0.767 (n=10) vs 0.767 (n=10)\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Novak Djokovic vs Carlos Alcaraz | Clay | G F\n",
      "  Novak Djokovic               10.8%\n",
      "  Carlos Alcaraz               89.2%\n",
      "  → Carlos Alcaraz wins (89.2%)\n",
      "  H2H: 5–5 | 2–1 on Clay\n",
      "  ELO: 2053 vs 2179 | Surface: 1936 vs 2016\n",
      "  Rank: 3 vs 1 | Pts: 5280 vs 13550\n",
      "  Surface WR: 0.700 (n=10) vs 0.767 (n=10)\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Novak Djokovic vs Jannik Sinner | Hard | G F\n",
      "  Novak Djokovic               7.3%\n",
      "  Jannik Sinner                92.7%\n",
      "  → Jannik Sinner wins (92.7%) ⚠️  SUSPICIOUS\n",
      "  H2H: 5–6 | 2–4 on Hard\n",
      "  ELO: 2053 vs 2240 | Surface: 2023 vs 2221\n",
      "  Rank: 3 vs 2 | Pts: 5280 vs 11400\n",
      "  Surface WR: 0.767 (n=10) vs 0.833 (n=10)\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Alexander Zverev vs Carlos Alcaraz | Clay | G F\n",
      "  Alexander Zverev             97.0%\n",
      "  Carlos Alcaraz               3.0%\n",
      "  → Alexander Zverev wins (97.0%) ⚠️  SUSPICIOUS\n",
      "  H2H: 6–7 | 1–3 on Clay\n",
      "  ELO: 1940 vs 2179 | Surface: 1822 vs 2016\n",
      "  Rank: 4 vs 1 | Pts: 4905 vs 13550\n",
      "  Surface WR: 0.567 (n=10) vs 0.767 (n=10)\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Daniil Medvedev vs Jannik Sinner | Hard | G F\n",
      "  Daniil Medvedev              9.6%\n",
      "  Jannik Sinner                90.4%\n",
      "  → Jannik Sinner wins (90.4%) ⚠️  SUSPICIOUS\n",
      "  H2H: 7–9 | 6–9 on Hard\n",
      "  ELO: 1934 vs 2240 | Surface: 1909 vs 2221\n",
      "  Rank: 10 vs 2 | Pts: 3610 vs 11400\n",
      "  Surface WR: 0.767 (n=10) vs 0.833 (n=10)\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Carlos Alcaraz vs Alexander Zverev | Clay | G F\n",
      "  Carlos Alcaraz               98.0%\n",
      "  Alexander Zverev             2.0%\n",
      "  → Carlos Alcaraz wins (98.0%) ⚠️  SUSPICIOUS\n",
      "  H2H: 7–6 | 3–1 on Clay\n",
      "  ELO: 2179 vs 1940 | Surface: 2016 vs 1822\n",
      "  Rank: 1 vs 4 | Pts: 13550 vs 4905\n",
      "  Surface WR: 0.767 (n=10) vs 0.567 (n=10)\n",
      "\n",
      "────────────────────────────────────────────────────────────\n",
      "Jannik Sinner vs Daniil Medvedev | Hard | G F\n",
      "  Jannik Sinner                95.5%\n",
      "  Daniil Medvedev              4.5%\n",
      "  → Jannik Sinner wins (95.5%) ⚠️  SUSPICIOUS\n",
      "  H2H: 9–7 | 9–6 on Hard\n",
      "  ELO: 2240 vs 1934 | Surface: 2221 vs 1909\n",
      "  Rank: 2 vs 10 | Pts: 11400 vs 3610\n",
      "  Surface WR: 0.833 (n=10) vs 0.767 (n=10)\n"
     ]
    }
   ],
   "source": [
    "def predict_matchup(p1_name, p2_name, surface='Hard', level='G', round_='F', best_of=5):\n",
    "    SURFACE_MAP = {'Hard':0,'Clay':1,'Grass':2,'Carpet':0}\n",
    "    LEVEL_MAP   = {'250':0,'500':1,'A':2,'M':3,'G':4,'D':5,'O':5,'F':6}\n",
    "    ROUND_MAP   = {'R128':1,'R64':2,'R32':3,'R16':4,'QF':5,'SF':6,'F':7,'RR':3}\n",
    "\n",
    "    surf_enc  = SURFACE_MAP.get(surface, 0)\n",
    "    level_enc = LEVEL_MAP.get(level, 4)\n",
    "    round_enc = ROUND_MAP.get(round_, 7)\n",
    "\n",
    "    def find_pid(name):\n",
    "        last = name.split()[-1]\n",
    "        w = df[df['winner_name'].str.contains(last, na=False)].sort_values('tourney_date')\n",
    "        l = df[df['loser_name'].str.contains(last, na=False)].sort_values('tourney_date')\n",
    "        if len(w) == 0 and len(l) == 0: return None\n",
    "        if len(w) == 0: return l.iloc[-1]['loser_id']\n",
    "        if len(l) == 0: return w.iloc[-1]['winner_id']\n",
    "        if w.iloc[-1]['tourney_date'] >= l.iloc[-1]['tourney_date']:\n",
    "            return w.iloc[-1]['winner_id']\n",
    "        return l.iloc[-1]['loser_id']\n",
    "\n",
    "    def get_features(pid, surf_enc):\n",
    "        w_rows = feature_df[feature_df['match_id'].isin(df[df['winner_id']==pid]['match_id'])].copy()\n",
    "        w_rows['_w'] = True\n",
    "        l_rows = feature_df[feature_df['match_id'].isin(df[df['loser_id']==pid]['match_id'])].copy()\n",
    "        l_rows['_w'] = False\n",
    "        all_rows = pd.concat([w_rows, l_rows]).sort_values('match_date')\n",
    "        if len(all_rows) == 0: return None\n",
    "\n",
    "        r = all_rows.iloc[-1]\n",
    "        w = r['_w']\n",
    "\n",
    "        # Surface-specific stats from last match on this surface\n",
    "        surf_rows = all_rows[all_rows['surface_enc'] == surf_enc]\n",
    "        if len(surf_rows) > 0:\n",
    "            rs = surf_rows.iloc[-1]; ws = rs['_w']\n",
    "            surface_elo = rs['w_surface_elo'] if ws else rs['l_surface_elo']\n",
    "            surface_wr  = rs['w_surface_wr']  if ws else rs['l_surface_wr']\n",
    "            surface_n   = rs['w_surface_n']   if ws else rs['l_surface_n']\n",
    "        else:\n",
    "            surface_elo = r['w_surface_elo'] if w else r['l_surface_elo']\n",
    "            surface_wr  = r['w_surface_wr']  if w else r['l_surface_wr']\n",
    "            surface_n   = 0\n",
    "\n",
    "        df_row = df[df['match_id']==r['match_id']].iloc[0]\n",
    "        return {\n",
    "            'recent_wr':   r['w_recent_wr']   if w else r['l_recent_wr'],\n",
    "            'recent_n':    r['w_recent_n']    if w else r['l_recent_n'],\n",
    "            'surface_wr':  surface_wr,\n",
    "            'surface_n':   surface_n,\n",
    "            'days_rest':   r['w_days_rest']   if w else r['l_days_rest'],\n",
    "            'matches_7d':  r['w_matches_7d']  if w else r['l_matches_7d'],\n",
    "            'matches_30d': r['w_matches_30d'] if w else r['l_matches_30d'],\n",
    "            'elo':         r['w_elo']         if w else r['l_elo'],\n",
    "            'surface_elo': surface_elo,\n",
    "            'rank':        df_row['winner_rank']        if w else df_row['loser_rank'],\n",
    "            'rank_points': df_row['winner_rank_points'] if w else df_row['loser_rank_points'],\n",
    "            'age':         df_row['winner_age']         if w else df_row['loser_age'],\n",
    "        }\n",
    "\n",
    "    p1_id = find_pid(p1_name)\n",
    "    p2_id = find_pid(p2_name)\n",
    "    if not p1_id or not p2_id:\n",
    "        print(f\"Player not found\"); return\n",
    "\n",
    "    f1 = get_features(p1_id, surf_enc)\n",
    "    f2 = get_features(p2_id, surf_enc)\n",
    "    if not f1 or not f2:\n",
    "        print(\"Could not extract features\"); return\n",
    "\n",
    "    # H2H\n",
    "    h2h   = df[((df['winner_id']==p1_id)&(df['loser_id']==p2_id))|\n",
    "                ((df['winner_id']==p2_id)&(df['loser_id']==p1_id))]\n",
    "    p1_wins   = (h2h['winner_id']==p1_id).sum()\n",
    "    total_h2h = len(h2h)\n",
    "    p1_h2h_wr = (p1_wins+1)/(total_h2h+2)\n",
    "\n",
    "    h2h_s       = h2h[h2h['surface_enc']==surf_enc]\n",
    "    p1_s_wins   = (h2h_s['winner_id']==p1_id).sum()\n",
    "    total_h2h_s = len(h2h_s)\n",
    "    p1_h2h_s_wr = (p1_s_wins+1)/(total_h2h_s+2)\n",
    "\n",
    "    row = {\n",
    "        'p1_rank': f1['rank'], 'p2_rank': f2['rank'],\n",
    "        'rank_diff': f2['rank']-f1['rank'],\n",
    "        'p1_rank_points': f1['rank_points'], 'p2_rank_points': f2['rank_points'],\n",
    "        'rank_points_diff': f1['rank_points']-f2['rank_points'],\n",
    "        'p1_age': f1['age'], 'p2_age': f2['age'], 'age_diff': f1['age']-f2['age'],\n",
    "        'surface': surf_enc, 'level': level_enc, 'indoor': 0,\n",
    "        'round': round_enc, 'best_of': best_of,\n",
    "        'p1_recent_wr': f1['recent_wr'], 'p2_recent_wr': f2['recent_wr'],\n",
    "        'recent_wr_diff': f1['recent_wr']-f2['recent_wr'],\n",
    "        'p1_recent_n': f1['recent_n'], 'p2_recent_n': f2['recent_n'],\n",
    "        'p1_surface_wr': f1['surface_wr'], 'p2_surface_wr': f2['surface_wr'],\n",
    "        'surface_wr_diff': f1['surface_wr']-f2['surface_wr'],\n",
    "        'p1_surface_n': f1['surface_n'], 'p2_surface_n': f2['surface_n'],\n",
    "        'p1_h2h_wr': p1_h2h_wr, 'p2_h2h_wr': 1-p1_h2h_wr,\n",
    "        'h2h_diff': p1_h2h_wr-(1-p1_h2h_wr), 'p1_h2h_n': total_h2h,\n",
    "        'p1_h2h_surface_wr': p1_h2h_s_wr, 'p2_h2h_surface_wr': 1-p1_h2h_s_wr,\n",
    "        'h2h_surface_diff': p1_h2h_s_wr-(1-p1_h2h_s_wr), 'p1_h2h_surface_n': total_h2h_s,\n",
    "        'p1_days_rest': f1['days_rest'], 'p2_days_rest': f2['days_rest'],\n",
    "        'rest_diff': f1['days_rest']-f2['days_rest'],\n",
    "        'p1_matches_7d': f1['matches_7d'], 'p2_matches_7d': f2['matches_7d'],\n",
    "        'matches_7d_diff': f1['matches_7d']-f2['matches_7d'],\n",
    "        'p1_matches_30d': f1['matches_30d'], 'p2_matches_30d': f2['matches_30d'],\n",
    "        'matches_30d_diff': f1['matches_30d']-f2['matches_30d'],\n",
    "        'p1_elo': f1['elo'], 'p2_elo': f2['elo'],\n",
    "        'elo_diff': f1['elo']-f2['elo'],\n",
    "        'p1_surface_elo': f1['surface_elo'], 'p2_surface_elo': f2['surface_elo'],\n",
    "        'surface_elo_diff': f1['surface_elo']-f2['surface_elo'],\n",
    "    }\n",
    "\n",
    "    X = pd.DataFrame([row])[feature_cols]\n",
    "    prob = model.predict_proba(X)[0]\n",
    "    p1_prob, p2_prob = prob[1], prob[0]\n",
    "    winner = p1_name if p1_prob > 0.5 else p2_name\n",
    "    conf   = max(p1_prob, p2_prob)\n",
    "    flag   = \" ⚠️  SUSPICIOUS\" if conf > 0.90 else \"\"\n",
    "\n",
    "    print(f\"\\n{'─'*60}\")\n",
    "    print(f\"{p1_name} vs {p2_name} | {surface} | {level} {round_}\")\n",
    "    print(f\"  {p1_name:<28} {p1_prob:.1%}\")\n",
    "    print(f\"  {p2_name:<28} {p2_prob:.1%}\")\n",
    "    print(f\"  → {winner} wins ({conf:.1%}){flag}\")\n",
    "    print(f\"  H2H: {p1_wins}–{total_h2h-p1_wins} | {p1_s_wins}–{total_h2h_s-p1_s_wins} on {surface}\")\n",
    "    print(f\"  ELO: {f1['elo']:.0f} vs {f2['elo']:.0f} | Surface: {f1['surface_elo']:.0f} vs {f2['surface_elo']:.0f}\")\n",
    "    print(f\"  Rank: {f1['rank']:.0f} vs {f2['rank']:.0f} | Pts: {f1['rank_points']:.0f} vs {f2['rank_points']:.0f}\")\n",
    "    print(f\"  Surface WR: {f1['surface_wr']:.3f} (n={f1['surface_n']:.0f}) vs {f2['surface_wr']:.3f} (n={f2['surface_n']:.0f})\")\n",
    "\n",
    "for args in matchups:\n",
    "    predict_matchup(*args)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "d9622829-cbd2-4f9c-942d-ddd01b661588",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "cwd: /Users/franciscolorenzo/Documents/Tennis-Predictor\n",
      "api exists: True\n",
      "sys.path[0]: /Users/franciscolorenzo/Documents/Tennis-Predictor\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import sys\n",
    "\n",
    "# change this to your actual project folder\n",
    "PROJECT_ROOT = \"/Users/franciscolorenzo/Documents/Tennis-Predictor\"\n",
    "\n",
    "os.chdir(PROJECT_ROOT)\n",
    "\n",
    "if PROJECT_ROOT not in sys.path:\n",
    "    sys.path.insert(0, PROJECT_ROOT)\n",
    "\n",
    "print(\"cwd:\", os.getcwd())\n",
    "print(\"api exists:\", os.path.exists(os.path.join(PROJECT_ROOT, \"api\")))\n",
    "print(\"sys.path[0]:\", sys.path[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "a6206ef7-8a3e-48ec-a5db-0aad20ce73e0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Imports worked\n"
     ]
    }
   ],
   "source": [
    "from api.database import SessionLocal, Player, EloRating, Match\n",
    "from api.main import (\n",
    "    find_player,\n",
    "    get_elo,\n",
    "    get_recent_wr,\n",
    "    get_h2h,\n",
    "    get_days_rest,\n",
    "    get_rank_and_points,\n",
    "    get_match_counts,\n",
    "    SURFACE_MAP,\n",
    "    LEVEL_MAP,\n",
    "    ROUND_MAP,\n",
    ")\n",
    "\n",
    "print(\"Imports worked\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "b04ff383-1fac-47a9-ad01-1977554a6dfe",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\"\"\"Model loading and prediction helpers.\n",
      "\n",
      "The API keeps the trained scikit-learn model and the saved feature order in\n",
      "memory so each request only has to build a feature vector and call\n",
      "`predict_proba`.\n",
      "\"\"\"\n",
      "\n",
      "import joblib\n",
      "import json\n",
      "import numpy as np\n",
      "from pathlib import Path\n",
      "\n",
      "MODEL_PATH = Path(__file__).parent.parent / \"model\" / \"tennis_model_v2.pkl\"\n",
      "FEATURES_PATH = Path(__file__).parent.parent / \"model\" / \"feature_cols.json\"\n",
      "\n",
      "# Load once at startup so requests do not repeatedly hit disk.\n",
      "model = joblib.load(MODEL_PATH)\n",
      "\n",
      "with open(FEATURES_PATH) as f:\n",
      "    feature_cols = json.load(f)\n",
      "\n",
      "def predict(features: dict) -> dict:\n",
      "    \"\"\"Run the saved model against a fully assembled matchup feature dict.\"\"\"\n",
      "\n",
      "    # The model was trained with a fixed column order, so we rebuild the\n",
      "    # incoming dict into that exact ordering before prediction.\n",
      "    X = np.array([[features[col] for col in feature_cols]])\n",
      "    \n",
      "    prob = model.predict_proba(X)[0]\n",
      "    p1_prob = round(float(prob[1]), 3)\n",
      "    p2_prob = round(float(prob[0]), 3)\n",
      "    \n",
      "    # Confidence is a simple presentation label based on how far the predicted\n",
      "    # probabilities are from a coin flip.\n",
      "    gap = abs(p1_prob - p2_prob)\n",
      "    if gap > 0.4:\n",
      "        confidence = \"high\"\n",
      "    elif gap > 0.2:\n",
      "        confidence = \"medium\"\n",
      "    else:\n",
      "        confidence = \"low\"\n",
      "    \n",
      "    return {\n",
      "        \"p1_win_probability\": p1_prob,\n",
      "        \"p2_win_probability\": p2_prob,\n",
      "        \"predicted_winner\": \"player1\" if p1_prob > 0.5 else \"player2\",\n",
      "        \"confidence\": confidence\n",
      "    }\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import inspect\n",
    "import api.model as model_module\n",
    "\n",
    "print(inspect.getsource(model_module))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "209131f2-e334-4b79-9e68-4e7758da9c9e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A vs B: {'p1_win_probability': 0.608, 'p2_win_probability': 0.392, 'predicted_winner': 'player1', 'confidence': 'medium'}\n",
      "B vs A: {'p1_win_probability': 0.764, 'p2_win_probability': 0.236, 'predicted_winner': 'player1', 'confidence': 'high'}\n",
      "player1 prob sum: 1.3719999999999999\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/franciscolorenzo/Documents/Tennis-Predictor/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names\n",
      "  warnings.warn(\n",
      "/Users/franciscolorenzo/Documents/Tennis-Predictor/venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but HistGradientBoostingClassifier was fitted with feature names\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "from api.model import predict\n",
    "\n",
    "pred_ab = predict(features_ab)\n",
    "pred_ba = predict(features_ba)\n",
    "\n",
    "print(\"A vs B:\", pred_ab)\n",
    "print(\"B vs A:\", pred_ba)\n",
    "print(\"player1 prob sum:\", pred_ab[\"p1_win_probability\"] + pred_ba[\"p1_win_probability\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "3aa91e08-c700-4164-bed1-754b41be3be4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "module attrs:\n",
      "FEATURES_PATH\n",
      "MODEL_PATH\n",
      "Path\n",
      "f\n",
      "feature_cols\n",
      "joblib\n",
      "json\n",
      "model\n",
      "np\n",
      "predict\n"
     ]
    }
   ],
   "source": [
    "import api.model as m\n",
    "\n",
    "print(\"module attrs:\")\n",
    "for name in dir(m):\n",
    "    if not name.startswith(\"_\"):\n",
    "        print(name)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "95f6b72c-9eb6-4266-bc1f-ccd69cc67a76",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found model-like object: model\n",
      "classes_ = [0 1]\n"
     ]
    }
   ],
   "source": [
    "import api.model as m\n",
    "\n",
    "for name in dir(m):\n",
    "    obj = getattr(m, name)\n",
    "    if hasattr(obj, \"classes_\"):\n",
    "        print(\"Found model-like object:\", name)\n",
    "        print(\"classes_ =\", obj.classes_)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c12abf13-06b0-4236-b997-836b33d95379",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
